version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: webshop-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshop
      MYSQL_PASSWORD: webshop123
    ports:
      - "3307:3306"   # host:container
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # seed script bij opstart

  backend:
    build: .
    container_name: webshop-backend
    ports:
      - "9090:8080"   # host:container
    env_file:
      - env.env
    depends_on:
      - db

  mongodb:
    image: mongo:7.0
    container_name: webshop-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: webshop_payments

volumes:
  db_data:
  mongo_data:
